minimumReleaseAgeExclude:
  - '@vizejs/native-darwin-arm64@0.434.0'
  - '@vizejs/native-darwin-x64@0.434.0'
  - '@vizejs/native-linux-arm64-gnu@0.434.0'
  - '@vizejs/native-linux-arm64-musl@0.434.0'
  - '@vizejs/native-linux-x64-gnu@0.434.0'
  - '@vizejs/native-linux-x64-musl@0.434.0'
  - '@vizejs/native-win32-arm64-msvc@0.434.0'
  - '@vizejs/native-win32-x64-msvc@0.434.0'
  - '@vizejs/native@0.434.0'
  - '@vizejs/unplugin@0.434.0'
  - '@vizejs/vite-plugin@0.434.0'
  - vize@0.434.0
